### ISSUE TITLE
CloudinaryException: public_id is invalid

### ISSUE THREAD

**Issue by hiendinhngoc** [GoGoCarl/paperclip-cloudinary#10]
I got this problem when upload new images: `public_id (/uploaded/images/images/53/original_14696773_1230106550395132_23944727_n) is invalid`. Here is my configuration: 
```
has_attached_file :image, :storage => :cloudinary, path: "/uploaded/:class/:attachment/:id/:style_:filename", styles: { thumb: "300x200#", large: "1024x768>"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
```
Any problem with my path?

**Comment by GoGoCarl** [comment]
Hi @hiendinhngoc,

Removing the leading slash from your path should fix your issue:

```ruby
has_attached_file :image, 
  :storage => :cloudinary, 
  path: "uploaded/:class/:attachment/:id/:style_:filename", 
  styles: { thumb: "300x200#", large: "1024x768>"}
validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
```

Hope that helps, and thank you for using paperclip-cloudinary!

**Comment by hiendinhngoc** [comment]
Thank you @GoGoCarl , when I removed the leading slash, the error came out, but images cannot be loaded correctly, please look at my image:
[this is my image](https://i.imgsafe.org/f56ac056d8.png)
PS: I'm working in my localhost environment.

**Comment by GoGoCarl** [comment]
Excellent, glad that worked for you.

Regarding the images, it appears perhaps there is an issue with your view code, so I would have to see that to make any suggestions on that front, but a declaration like this should work:

```ruby
<%= image_tag @image.image.url(:thumb) %>
```

**Comment by hiendinhngoc** [comment]
You were right, in my view code, I used: 
`image_tag @image.image.path(:thumb)`
coz I supposed that it should be the same as `path` which I've set on image model. It's my other mistake, thank you so much for your help @GoGoCarl

**Comment by GoGoCarl** [comment]
Glad I could help!

**Comment by kashishgupta1990** [comment]
I am getting `public_id (MAKER/PRODUCT_IMAGE/1 ) is invalid` don't know why? need help 

Thanks

**Comment by GoGoCarl** [comment]
Hi @kashishgupta1990!

According to the [Cloudinary docs](https://cloudinary.com/documentation/upload_images):

> Note The Public ID format supports all printable characters except for the following reserved characters: ? & # \ % < >. In addition, **spaces** and forward slashes (/) **cannot be used as the first or last character** of the Public ID.

It appears that your ID has a trailing space at the end, perhaps unintentionally.

That would likely be the source of the issue.

Hope that helps!
