### ISSUE TITLE
unexpected tSYMBEG

### ISSUE THREAD

**Issue by aldompe95** [GoGoCarl/paperclip-cloudinary#11]
i have my model:
```
class Chef < ApplicationRecord
  belongs_to :restaurant

  validates :name, presence: true
  validates :avatar,
    attachment_content_type: { content_type: /\Aimage\/.*\Z/ },
    attachment_size: { less_than: 5.megabytes },

  has_attached_file :avatar, 
    :storage => :cloudinary
    
end
```
and it give me this error 
`syntax error, unexpected tSYMBEG, expecting keyword_do or '{' or '(' has_attached_file :avatar, ^`
in this line 
`has_attached_file :avatar, `

**Comment by GoGoCarl** [comment]
Hi there,

Looks like a syntax issue on line 7 above:

```ruby
attachment_size: { less_than: 5.megabytes },
```

Remove the comma at the end of that line and you should be set.

**Comment by aldompe95** [comment]
@GoGoCarl thanks man what a dumb i am

**Comment by GoGoCarl** [comment]
No worries, happens to us all!
