### ISSUE TITLE
Style not working 

### ISSUE THREAD

**Issue by aldompe95** [GoGoCarl/paperclip-cloudinary#12]
I have this style on the images
```
has_attached_file :avatar,
    :storage => :cloudinary,
    :path => "dishes/:filename",
    :styles => {
      :thumb => '100x100>',
      :square => '200x200#',
      :medium => '300x300>'
    }
```
and then i call them like this:
 `<%= image_tag dish.avatar.url(:medium), :class => 'img-responsive imgCenter' %>`
but its not showing the right size

**Comment by GoGoCarl** [comment]
Hi @aldompe95,

You may want to check the actual URL generated from `dish.avatar.url(:medium)` to ensure the right image is being returned.  I suspect that the sizing issue may be from setting the class to `img-responsive`.  That can make the image stretch or shrink to fit the container's space.
